[package]
name = "ieee80211"
version = "0.1.0"
edition = "2021"

[dependencies]
crc32fast = { version = "1.3.2", default-features = false }
heapless = "0.7.16"
mac-parser = { git = "https://github.com/Frostie314159/mac-parser.git", version = "0.1.3" }
macro-bits = "0.1.4"
scroll = { git = "https://github.com/Frostie314159/scroll.git", branch = "no-unsafe", version = "0.11.0", default-features = false, features = ["derive"] }
tlv-rs = { version = "0.2.3", default-features = false, path = "../tlv-rs" }
