[package]
name = "ieee80211"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
crc32fast = { version = "1.3.2", default-features = false }
either = { version = "1.9.0", default-features = false }
mac-parser = { git = "https://github.com/Frostie314159/mac-parser.git" }
macro-bits = "0.1.4"
scroll = { git = "https://github.com/Frostie314159/scroll.git", branch = "fixed-array-impl", default-features = false }
tlv-rs = { default-features = false, git = "https://github.com/Frostie314159/tlv-rs" }
